"""Three Knots: why a spine IK curve needs three knots (MOTION_EDIT_RIG.md section 15).

Planar picture. A C1 piecewise-cubic Hermite curve, joints placed by arc length.
Render: uv run manim -qh --disable_caching three_knots.py ThreeKnots
"""
from moted_style import *
import numpy as np
from scipy.optimize import minimize

SX, SY, SC = -3.4, -2.5, 1.2          # local pose coords -> screen
TS = (0.0, 0.4, 1.0)           # knot parameters (mid takes its own arc fraction)
NJ = 6                         # joints in the chain


def scr(p):
    return np.array([p[0] * SC + SX, p[1] * SC + SY, 0.0])


def herm(p0, p1, m0, m1, dt, s):
    s = np.asarray(s)[:, None]
    h00 = 2 * s**3 - 3 * s**2 + 1
    h10 = s**3 - 2 * s**2 + s
    h01 = -2 * s**3 + 3 * s**2
    h11 = s**3 - s**2
    return h00 * p0 + h10 * dt * m0 + h01 * p1 + h11 * dt * m1


def curve3(P0, T0, M, T1, C, T2, n=240):
    """Three-knot curve (dP/dt tangents). Returns dense points."""
    a = herm(P0, M, T0, T1, TS[1], np.linspace(0, 1, n))
    b = herm(M, C, T1, T2, TS[2] - TS[1], np.linspace(0, 1, n))
    return np.vstack([a, b[1:]])


def place(pts, nj=NJ):
    """Joints at equal arc-length fractions along the dense curve."""
    seg = np.linalg.norm(np.diff(pts, axis=0), axis=1)
    cum = np.concatenate([[0], np.cumsum(seg)])
    want = np.linspace(0, cum[-1], nj)
    return np.stack([np.interp(want, cum, pts[:, 0]), np.interp(want, cum, pts[:, 1])], 1)


# --- the pose: generated by a three-knot curve, so it is reachable by construction
P0 = np.array([0.0, 0.0]); C = np.array([0.3, 4.2])
M_T = np.array([-1.0, 1.75])
T0_T = np.array([-1.3, 3.2]); T1_T = np.array([0.1, 4.6]); T2_T = np.array([2.2, 3.0])
true_pts = curve3(P0, T0_T, M_T, T1_T, C, T2_T)
TARGET = place(true_pts)


def two_knot_state(T0, T2):
    """A single cubic P0..C, re-expressed as a three-knot state at t=0.4 (exact)."""
    s = 0.4
    M = herm(P0, C, T0, T2, 1.0, [s])[0]
    ds = 1e-5
    d = (herm(P0, C, T0, T2, 1.0, [s + ds])[0] - herm(P0, C, T0, T2, 1.0, [s - ds])[0]) / (2 * ds)
    return M, T0, d, T2


def miss2(x):
    M, T0, T1, T2 = two_knot_state(x[:2], x[2:])
    return np.sum((place(curve3(P0, T0, M, T1, C, T2)) - TARGET) ** 2)


def best_two_knot():
    best = None
    rng = np.random.default_rng(3)
    for _ in range(12):
        r = minimize(miss2, rng.uniform(-3, 3, 4), method="Nelder-Mead",
                     options=dict(xatol=1e-7, fatol=1e-12, maxiter=4000))
        if best is None or r.fun < best.fun:
            best = r
    return best.x


BEST2 = best_two_knot()
TRUE_STATE = (M_T, T0_T, T1_T, T2_T)


class ThreeKnots(Scene):
    # ---------- geometry helpers ----------
    def state(self):
        s2 = two_knot_state(np.array([self.t0x.get_value(), self.t0y.get_value()]),
                            np.array([self.t2x.get_value(), self.t2y.get_value()]))
        b = self.blend.get_value()
        return tuple((1 - b) * np.asarray(a) + b * np.asarray(t) for a, t in zip(s2, TRUE_STATE))

    def dense(self):
        M, T0, T1, T2 = self.state()
        return curve3(P0, T0, M, T1, C, T2)

    def make_curve(self, color=YELLOW, width=5):
        def f():
            m = VMobject(stroke_color=color, stroke_width=width)
            m.set_points_as_corners([scr(p) for p in self.dense()[::3]])
            return m
        return always_redraw(f)

    def make_fit(self):
        def f():
            g = VGroup()
            j = place(self.dense())
            for k in range(NJ):
                g.add(Dot(scr(j[k]), radius=0.08, color=YELLOW))
            return g
        return always_redraw(f)

    def make_miss(self):
        def f():
            g = VGroup()
            j = place(self.dense())
            for k in range(NJ):
                d = np.linalg.norm(j[k] - TARGET[k])
                if d > 0.015:
                    g.add(Line(scr(TARGET[k]), scr(j[k]), color=RED, stroke_width=4))
            return g
        return always_redraw(f)

    def knots(self):
        def f():
            M = self.state()[0]
            g = VGroup(Dot(scr(P0), radius=0.14, color=ORANGE), Dot(scr(C), radius=0.14, color=ORANGE))
            if self.show_mid:
                g.add(Dot(scr(M), radius=0.14, color=ORANGE))
            return g
        return always_redraw(f)

    def side(self, tex_list, x=2.6, y0=2.3, gap=0.95, **kw):
        g = VGroup(*tex_list).arrange(DOWN, aligned_edge=LEFT, buff=0.38)
        g.move_to([x, y0 - g.height / 2, 0], aligned_edge=UP + LEFT) if False else None
        return g

    def tag(self, text, prev=None):
        t = Text(text, font_size=26, color=DIM).to_corner(UL, buff=0.45)
        if prev is None:
            self.play(FadeIn(t), run_time=0.5)
        else:
            self.play(ReplacementTransform(prev, t), run_time=0.5)
        return t

    # ---------- the film ----------
    def construct(self):
        self.show_mid = False
        self.t0x, self.t0y, self.t2x, self.t2y = [ValueTracker(0) for _ in range(4)]
        self.blend = ValueTracker(0)
        self.t0x.set_value(0.0); self.t0y.set_value(1.5)
        self.t2x.set_value(0.0); self.t2y.set_value(1.5)

        title_card(self, "Three Knots", "Count what a representation can reach")

        # ===== Beat 1: a chain, and a curve it wants =====
        tg = self.tag("1   A spine at rest")
        bones = VGroup(*[Line(scr(TARGET[i]), scr(TARGET[i + 1]), color=BLUE, stroke_width=6)
                         for i in range(NJ - 1)])
        joints = VGroup(*[Dot(scr(TARGET[i]), radius=0.13, color=BLUE) for i in range(NJ)])
        cap = caption(self, "A spine is a chain of joints.")
        self.play(LaggedStart(*[FadeIn(joints[i], scale=0.5) for i in range(NJ)], lag_ratio=0.2),
                  LaggedStart(*[Create(bones[i]) for i in range(NJ - 1)], lag_ratio=0.2), run_time=2.4)
        self.wait(1)
        cap = caption(self, "An IK spine wants one smooth curve for them to follow.", cap)
        self.t0x.set_value(BEST2[0]); self.t0y.set_value(BEST2[1])
        self.t2x.set_value(BEST2[2]); self.t2y.set_value(BEST2[3])
        ghost = self.make_curve(color=DIM, width=4)
        self.play(Create(ghost), run_time=2)
        self.wait(1)
        cap = caption(self, "The curve is built from a few controls: knots.", cap)
        kn = VGroup(Dot(scr(P0), radius=0.15, color=ORANGE), Dot(scr(C), radius=0.15, color=ORANGE))
        kl = VGroup(Text("pelvis knot", font_size=24, color=ORANGE).next_to(scr(P0), LEFT, buff=0.3),
                    Text("chest knot", font_size=24, color=ORANGE).next_to(scr(C), RIGHT, buff=0.3))
        self.play(FadeIn(kn, scale=2), FadeIn(kl), run_time=1)
        self.wait(1.5)

        # ===== Beat 2: two knots cannot reach the pose =====
        tg = self.tag("2   Two knots", tg)
        cap = caption(self, "Joints are fitted along the curve. Let it try to hit them all.", cap)
        self.remove(ghost)
        rings = VGroup(*[Circle(radius=0.17, color=BLUE, stroke_width=4).move_to(scr(TARGET[i]))
                         for i in range(NJ)])
        self.play(FadeOut(joints), FadeIn(rings), run_time=0.8)
        crv = self.make_curve(); fit = self.make_fit(); miss = self.make_miss()
        self.add(crv, miss, fit)
        self.remove(kn)
        knots_live = self.knots(); self.add(knots_live)
        # panel: counting
        e1 = MathTex(r"\text{joints to hit: } 4 \times 2 = 8", font_size=38)
        e2 = MathTex(r"\text{curve freedom: } 2 \text{ tangents} = 4", font_size=38)
        e3 = MathTex(r"4 < 8", font_size=56, color=RED)
        panel = VGroup(e1, e2, e3).arrange(DOWN, aligned_edge=LEFT, buff=0.55).move_to([3.3, 0.3, 0])
        # tries
        tries = [(-2.5, 2.5, 2.5, 2.5), (2.8, 0.4, -2.8, 1.0), tuple(BEST2)]
        for k, tr in enumerate(tries):
            self.play(*[t.animate.set_value(v) for t, v in
                        zip((self.t0x, self.t0y, self.t2x, self.t2y), tr)], run_time=2.2, rate_func=smooth)
            if k == 0:
                self.play(Write(e1), run_time=1.2)
            if k == 1:
                self.play(Write(e2), run_time=1.2)
            self.wait(0.6)
        cap = caption(self, "Two knots: more joints to hit than the curve can bend.", cap)
        self.play(Write(e3), run_time=0.8)
        note = VGroup(Text("S-curve pose, measured:", font_size=22, color=DIM), Text("worst miss 1.158 cm", font_size=22, color=DIM)).arrange(DOWN, aligned_edge=LEFT, buff=0.1)
        note.next_to(panel, DOWN, buff=0.6, aligned_edge=LEFT)
        self.play(FadeIn(note))
        self.wait(4)

        # ===== Beat 3: add the mid knot =====
        tg = self.tag("3   Add a third point", tg)
        cap = caption(self, "Fix a third point: the mid knot.", cap)
        self.play(FadeOut(VGroup(e1, e2, e3, note)), run_time=0.6)
        self.show_mid = True
        ml = Text("mid knot", font_size=24, color=ORANGE)
        ml.next_to(scr(M_T), LEFT, buff=0.3)
        self.play(FadeIn(ml), run_time=0.6)
        u1 = MathTex(r"\text{unknowns: } 2 + 3 \times 2 = 8", font_size=38)
        u2 = MathTex(r"\text{equations: } 4 \times 2 = 8", font_size=38)
        u3 = MathTex(r"8 = 8", font_size=56, color=GREEN)
        panel3 = VGroup(u1, u2, u3).arrange(DOWN, aligned_edge=LEFT, buff=0.55).move_to([3.3, 0.3, 0])
        self.play(Write(u1), run_time=1.2)
        self.play(Write(u2), run_time=1.2)
        self.wait(0.5)
        cap = caption(self, "Constraints now match the unknowns. The fit is exact.", cap)
        self.play(self.blend.animate.set_value(1), run_time=4, rate_func=smooth)
        self.play(Write(u3), run_time=0.8)
        self.play(*[r.animate.set_color(GREEN) for r in rings], run_time=0.6)
        sq = Text("square: exact, not a best guess", font_size=24, color=GREEN)
        sq.next_to(panel3, DOWN, buff=0.5, aligned_edge=LEFT)
        nz = Text("miss: float noise (4.5e-12 cm)", font_size=22, color=DIM)
        nz.next_to(sq, DOWN, buff=0.25, aligned_edge=LEFT)
        self.play(FadeIn(sq), FadeIn(nz))
        self.wait(1.5)
        cap = caption(self, "Count what a representation can reach.", cap, font_size=40)
        self.wait(5)

        # ===== Beat 4: shape, but no roll =====
        tg = self.tag("4   Shape, but no roll", tg)
        self.play(FadeOut(VGroup(panel3, sq, nz, ml)), run_time=0.6)
        cap = caption(self, "Now twist the chain about its own axis.", cap)
        frozen = VMobject(stroke_color=DIM, stroke_width=2)
        frozen.set_points_as_corners([scr(p) for p in self.dense()[::3]])
        fitdots = VGroup(*[Dot(scr(p), radius=0.08, color=YELLOW) for p in place(self.dense())])
        self.remove(crv, fit, miss, knots_live)
        live = frozen.copy().set_color(YELLOW).set_stroke(width=5)
        kn3 = VGroup(*[Dot(scr(p), radius=0.14, color=ORANGE) for p in (P0, M_T, C)])
        self.add(live, kn3, fitdots)
        self.play(FadeOut(rings), FadeIn(joints), run_time=0.6)
        self.add(frozen)
        dials = VGroup(); marks = []
        ys = [1.9, 0.9, -0.1, -1.1]
        for y in ys:
            c = Circle(radius=0.32, color=BLUE, stroke_width=4).move_to([2.4, y, 0])
            ln = Line(c.get_center(), c.get_center() + UP * 0.32, color=BLUE, stroke_width=6)
            dials.add(VGroup(c, ln)); marks.append(ln)
        end_lbl = Text("seen end-on, per joint", font_size=22, color=DIM).next_to(dials, UP, buff=0.3).align_to(dials, LEFT)
        self.play(FadeIn(dials), FadeIn(end_lbl))
        self.play(*[Rotate(m, angle=a_, about_point=m.get_start()) for m, a_ in
                    zip(marks, [-0.7, -1.2, -0.4, -1.0])], run_time=2.4)
        self.wait(0.6)
        cap = caption(self, "The curve does not change at all.", cap)
        chk = Text("curve: identical", font_size=26, color=GREEN)
        chk.move_to([4.9, 0.6, 0])
        self.play(Indicate(live, color=GREEN, scale_factor=1.0), FadeIn(chk), run_time=1.2)
        self.wait(2)
        cap = caption(self, "A curve carries shape but no roll.", cap)
        self.wait(2)
        cap = caption(self, "So twist must be carried on RO_Twist channels.", cap)
        self.play(FadeOut(chk), FadeOut(end_lbl), run_time=0.4)
        tl = VGroup(*[Text(f"RO_Twist 0{i+1}", font_size=24, color=BLUE).next_to(dials[i], RIGHT, buff=0.35)
                      for i in range(4)])
        self.play(LaggedStart(*[FadeIn(t, shift=LEFT * 0.2) for t in tl], lag_ratio=0.3), run_time=1.6)
        self.wait(4)

        # ===== Beat 5: the decision as built =====
        tg = self.tag("5   As built: two knots", tg)
        everything = Group(*[m for m in self.mobjects if m is not cap and m is not tg])
        self.play(FadeOut(everything), run_time=0.8)
        cap = caption(self, "The shipped rig makes a simpler choice: two knots, mid and chest.", cap, font_size=28)
        PT = np.array([[-0.6 * np.sin(np.pi * i / 5) + 0.0, i * 0.84] for i in range(NJ)])
        bones5 = VGroup(*[Line(scr(PT[i]), scr(PT[i + 1]), color=(GREEN if i >= 3 else BLUE), stroke_width=6)
                          for i in range(NJ - 1)])
        joints5 = VGroup(*[Dot(scr(PT[i]), radius=0.13, color=(GREEN if i > 3 else BLUE)) for i in range(NJ)])
        self.play(FadeIn(bones5), FadeIn(joints5), run_time=1)
        p1, p3 = PT[1], PT[3]
        mid_pt = (p1 + p3) / 2
        Aa = p3 - p1
        Dd = 4 * (PT[2] - mid_pt)
        Ta, Tb = Aa + Dd, Aa - Dd
        seg = herm(p1, p3, Ta, Tb, 1.0, np.linspace(0, 1, 120))
        curve5 = VMobject(stroke_color=YELLOW, stroke_width=5)
        curve5.set_points_as_corners([scr(p) for p in seg])
        knots5 = VGroup(Dot(scr(p1), radius=0.16, color=ORANGE), Dot(scr(p3), radius=0.16, color=ORANGE))
        L_mid = Text("mid knot", font_size=24, color=ORANGE).next_to(scr(p1), LEFT, buff=0.3)
        L_chest = Text("chest knot", font_size=24, color=ORANGE).next_to(scr(p3), LEFT, buff=0.3)
        self.play(Create(curve5), FadeIn(knots5, scale=2), FadeIn(L_mid), FadeIn(L_chest), run_time=2)
        seg_l = Text("one segment", font_size=24, color=YELLOW).move_to(scr(PT[2]) + np.array([1.5, 0, 0]))
        self.play(FadeIn(seg_l))
        self.wait(2)
        cap = caption(self, "The pelvis is not a knot: it swings on a hip pendulum.", cap, font_size=28)
        arc = Arc(radius=0.9, start_angle=PI * 0.15, angle=PI * 0.7, color=ORANGE, stroke_width=4).move_arc_center_to(scr(PT[1]))
        arc.shift(DOWN * 0.0)
        arc = Arc(radius=0.7, start_angle=PI * 1.15, angle=PI * 0.7, color=ORANGE, stroke_width=4).move_arc_center_to(scr(PT[1]))
        arc.add_tip(tip_length=0.18)
        L_hip = Text("pelvis: hip pendulum", font_size=24, color=ORANGE).next_to(scr(PT[0]), LEFT, buff=0.3).shift(DOWN * 0.1)
        self.play(Create(arc), FadeIn(L_hip), run_time=1.5)
        self.wait(2)
        cap = caption(self, "Joints between the knots are fitted. Above the chest, a rigid ribcage.", cap, font_size=28)
        L_fit = Text("fitted joint", font_size=24, color=YELLOW).next_to(scr(PT[2]), RIGHT, buff=0.35).shift(RIGHT * 0.0)
        L_rib = Text("rigid ribcage", font_size=24, color=GREEN).next_to(scr((PT[4] + PT[5]) / 2), RIGHT, buff=0.45)
        self.play(FadeOut(seg_l), FadeIn(L_fit), FadeIn(L_rib), run_time=1)
        self.wait(2.5)
        cap = caption(self, "Rest calibration: tangents chosen so the curve passes through rest.", cap, font_size=28)
        val = Text("RO_Offset   0.000", font_size=30, color=GREEN).move_to([3.8, 1.2, 0])
        sub = Text("every residual reads 0 at rest", font_size=22, color=DIM).next_to(val, DOWN, buff=0.25, aligned_edge=LEFT)
        self.play(FadeIn(val), FadeIn(sub), run_time=1)
        self.wait(2.5)
        cap = caption(self, "What the one segment cannot reach goes on RO_Offset.", cap, font_size=28)
        j2 = joints5[2]
        newpos = scr(PT[2]) + np.array([0.45, 0.12, 0])
        cpt = scr(PT[2])
        off = Line(cpt, newpos, color=ORANGE, stroke_width=5)
        bones_bend = VGroup(Line(scr(PT[1]), newpos, color=BLUE, stroke_width=6),
                            Line(newpos, scr(PT[3]), color=BLUE, stroke_width=6))
        self.play(FadeOut(bones5[1]), FadeOut(bones5[2]), FadeOut(L_fit), j2.animate.move_to(newpos),
                  FadeIn(bones_bend), run_time=1.5)
        val2 = Text("RO_Offset   carries the miss", font_size=30, color=ORANGE).move_to(val, aligned_edge=LEFT)
        self.play(Create(off), Transform(val, val2), FadeOut(sub), run_time=1.2)
        self.wait(3)

        # ===== Ledger =====
        everything = Group(*[m for m in self.mobjects if m is not cap and m is not tg])
        self.play(FadeOut(everything), FadeOut(tg), run_time=0.8)
        cap = caption(self, "The ledger.", cap)
        L = [("shape", "what the curve reaches", GREEN),
             ("+ offset", "RO_Offset per fitted joint: what the curve misses", ORANGE),
             ("+ twist", "RO_Twist: what a curve cannot carry (roll)", BLUE)]
        rowsL = VGroup()
        for i, (a_, b_, col) in enumerate(L):
            y = 1.2 - i * 1.3
            ta = Text(a_, font_size=40, weight=BOLD, color=col).move_to([-5.9, y, 0], aligned_edge=LEFT)
            tb = Text(b_, font_size=28, color=INK).move_to([-2.6, y, 0], aligned_edge=LEFT)
            rowsL.add(VGroup(ta, tb))
        for r in rowsL:
            self.play(FadeIn(r[0], shift=RIGHT * 0.3), FadeIn(r[1], shift=RIGHT * 0.3), run_time=1)
            self.wait(1.5)
        self.wait(2)
        self.play(FadeOut(rowsL), FadeOut(cap), run_time=0.8)

        # ===== End card =====
        lines = [Text("Count what the curve can reach.", font_size=44, color=GREEN),
                 Text("Carry the rest on channels.", font_size=44, color=YELLOW)]
        eg = VGroup(*lines).arrange(DOWN, buff=0.7)
        for l in lines:
            self.play(FadeIn(l, shift=UP * 0.2), run_time=1)
            self.wait(1.5)
        self.wait(5)
        self.play(FadeOut(eg))
